name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GCC and Make
        run: |
          sudo apt update
          sudo apt install -y gcc make

      - name: Build the project
        run: make VERBOSE=1

      - name: Run the program
        run: ./bin/sensor_program

      - name: Clean up
        run: make clean
